apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gershman-daniel-dev/actual-budget
    targetRevision: HEAD
    path: "./"
  destination:
    server: https://kubernetes.default.svc
    namespace: actual-budget

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
