apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-app-of-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gershman-daniel-dev/argo-cd-app-of-apps.git
    targetRevision: HEAD
    path: "./apps"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd-app-of-apps

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
