apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-chart
  namespace: plex-chart
spec:
  project: default

  source:
    repoURL: https://github.com/gershman-daniel-dev/plex-chart
    targetRevision: HEAD
    path: "./"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-apps

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
